version: "3"
services:
  cms:
    image: taccwma/frontera-cms:c0173cc
    volumes:
      - ./conf/cms/secrets.py:/code/taccsite_cms/secrets.py
      - ./conf/uwsgi/uwsgi_cms.ini:/code/uwsgi.ini
      - /var/www/frontera/cms/static:/code/static
      - /var/www/frontera/cms/media:/code/media
    command: ["uwsgi", "--ini", "uwsgi.ini"]
    container_name: frontera_cms
    logging:
      driver: syslog
      options:
        tag: portal_cms
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/uwsgi/uwsgi_params:/etc/nginx/uwsgi_params
      - /etc/ssl/certs/pprd.frontera-portal.tacc.utexas.edu.cer:/etc/ssl/certs/portal.cer
      - /etc/ssl/private/pprd.frontera-portal.tacc.utexas.edu.key:/etc/ssl/private/portal.key
      - /etc/ssl/dhparam.pem:/etc/ssl/dhparam.pem
      - /var/www/frontera/cms/static:/var/www/frontera/cms/static
      - /var/www/frontera/cms/media:/var/www/frontera/cms/media
      - /var/www/frontera/portal/media:/var/www/frontera/portal/media
      - /var/www/frontera/portal/static:/var/www/frontera/portal/static
      - /var/www/frontera/docs:/var/www/frontera/docs
    ports:
      - 80:80
      - 443:443
    container_name: frontera_nginx
    logging:
      driver: syslog
      options:
        tag: portal_nginx
    restart: always

  memcached:
    image: memcached:latest
    command: ["-m", "1024m"]
    container_name: frontera_memcached
    restart: always

  redis:
    image: redis:5.0
    volumes:
      - frontera_redis_data:/data
    container_name: frontera_redis
    logging:
      driver: syslog
      options:
        tag: portal_redis
    restart: always

  rabbitmq:
    image: rabbitmq:3.7.17-management
    volumes:
      - frontera_rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@frontera_rabbitmq
    env_file: ./conf/rabbitmq/rabbitmq.env
    container_name: frontera_rabbitmq
    logging:
      driver: syslog
      options:
        tag: portal_rabbitmq
    restart: always

  websockets:
    image: taccwma/frontera-portal:${FRONTERA_PORTAL_TAG}
    command: 'daphne -b 0.0.0.0 -p 9000 -e ssl:443:privateKey=/etc/ssl/private/portal.key:certKey=/etc/ssl/certs/portal.cer --root-path=/srv/www/portal/server --access-log - --proxy-headers portal.asgi:application'
    volumes:
      - ./conf/portal/settings_secret.py:/srv/www/portal/server/portal/settings/settings_secret.py
      - /etc/ssl/certs/pprd.frontera-portal.tacc.utexas.edu.cer:/etc/ssl/certs/portal.cer
      - /etc/ssl/private/pprd.frontera-portal.tacc.utexas.edu.key:/etc/ssl/private/portal.key
    container_name: frontera_websockets
    logging:
      driver: syslog
      options:
        tag: portal_websockets
    restart: always

  core:
    image: taccwma/frontera-portal:${FRONTERA_PORTAL_TAG}
    volumes:
      - ./conf/portal/settings_secret.py:/srv/www/portal/server/portal/settings/settings_secret.py
      - /var/www/frontera/portal/media:/srv/www/portal/server/media
      - /var/www/frontera/portal/static:/srv/www/portal/server/static
      - ./conf/uwsgi/uwsgi_core.ini:/srv/www/portal/server/conf/uwsgi/uwsgi_core.ini
    stdin_open: true
    tty: true
    command: uwsgi --ini /srv/www/portal/server/conf/uwsgi/uwsgi_core.ini
    container_name: frontera_django
    logging:
      driver: syslog
      options:
        tag: portal_django
    restart: always

  workers:
    image: taccwma/frontera-portal:${FRONTERA_PORTAL_TAG}
    volumes:
      - ./conf/portal/settings_secret.py:/srv/www/portal/server/portal/settings/settings_secret.py
    command: "celery -A portal worker -Q default,indexing,files,api,onboard --concurrency=10"
    container_name: frontera_workers
    logging:
      driver: syslog
      options:
        tag: portal_workers
    restart: always

  docs:
    image: taccwma/frontera-docs:8849bc2
    volumes:
      - /var/www/frontera/docs:/docs/site
    command: ["mkdocs", "build"]
    container_name: frontera_docs
    logging:
      driver: syslog
      options:
        tag: portal_user_guide

volumes:
  frontera_redis_data:
  frontera_es_data:
  frontera_rabbitmq_data:
