version: "3.8"
services:
  cms:
    image: ${CMS_IMAGE}:${CMS_TAG}
    volumes:
      - ./conf/cms/settings_secret.py:/code/taccsite_cms/settings_secret.py
      - ./conf/cms/settings_custom.py:/code/taccsite_cms/settings_custom.py
      - ./conf/uwsgi/uwsgi_cms.ini:/code/uwsgi.ini
      - /var/www/portal/cms/static:/code/static
      - /var/www/portal/cms/media:/code/media
    command: ["uwsgi", "--ini", "uwsgi.ini"]
    container_name: portal_cms
    logging:
      driver: syslog
      options:
        tag: portal_cms
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/uwsgi/uwsgi_params:/etc/nginx/uwsgi_params
      - /etc/ssl/dhparam.pem:/etc/ssl/dhparam.pem
      - /var/www/portal/cms/static:/var/www/portal/cms/static
      - /var/www/portal/cms/media:/var/www/portal/cms/media
      - /var/www/portal/portal/media:/var/www/portal/portal/media
      - /var/www/portal/portal/static:/var/www/portal/portal/static
    ports:
      - 80:80
      - 443:443
    container_name: portal_nginx
    logging:
      driver: syslog
      options:
        tag: portal_nginx
    restart: always

  memcached:
    image: memcached:latest
    command: ["-m", "1024m"]
    container_name: portal_memcached
    restart: always

  redis:
    image: redis:5.0
    volumes:
      - portal_redis_data:/data
    container_name: portal_redis
    logging:
      driver: syslog
      options:
        tag: portal_redis
    restart: always

  rabbitmq:
    image: rabbitmq:3.7.17-management
    volumes:
      - portal_rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@portal_rabbitmq
    env_file: ./conf/rabbitmq/rabbitmq.env
    container_name: portal_rabbitmq
    logging:
      driver: syslog
      options:
        tag: portal_rabbitmq
    restart: always

  websockets:
    image: ${PORTAL_IMAGE}:${PORTAL_TAG}
    command: 'daphne -b 0.0.0.0 -p 9000 -e ssl:443:privateKey=/etc/ssl/private/portal.key:certKey=/etc/ssl/certs/portal.cer --root-path=/srv/www/portal/server --access-log - --proxy-headers portal.asgi:application'
    volumes:
      - ./conf/portal/settings_secret.py:/srv/www/portal/server/portal/settings/settings_secret.py
      - ./conf/portal/settings_custom.py:/srv/www/portal/server/portal/settings/settings_custom.py
    container_name: portal_websockets
    logging:
      driver: syslog
      options:
        tag: portal_websockets
    restart: always

  core:
    image: ${PORTAL_IMAGE}:${PORTAL_TAG}
    volumes:
      - ./conf/portal/settings_secret.py:/srv/www/portal/server/portal/settings/settings_secret.py
      - ./conf/portal/settings_custom.py:/srv/www/portal/server/portal/settings/settings_custom.py
      - /var/www/portal/portal/media:/srv/www/portal/server/media
      - /var/www/portal/portal/static:/srv/www/portal/server/static
      - ./conf/uwsgi/uwsgi_core.ini:/srv/www/portal/server/conf/uwsgi/uwsgi_core.ini
    stdin_open: true
    tty: true
    command: uwsgi --ini /srv/www/portal/server/conf/uwsgi/uwsgi_core.ini
    container_name: portal_django
    logging:
      driver: syslog
      options:
        tag: portal_django
    restart: always

  workers:
    image: ${PORTAL_IMAGE}:${PORTAL_TAG}
    volumes:
      - ./conf/portal/settings_secret.py:/srv/www/portal/server/portal/settings/settings_secret.py
      - ./conf/portal/settings_custom.py:/srv/www/portal/server/portal/settings/settings_custom.py
    command: "celery -A portal worker -Q default,indexing,files,api,onboard --concurrency=10"
    container_name: portal_workers
    logging:
      driver: syslog
      options:
        tag: portal_workers
    restart: always

volumes:
  portal_redis_data:
  portal_es_data:
  portal_rabbitmq_data:
