version: "3.8"
services:
  nginx:
    extends:
      file: ${CAMINO_HOME}/conf/compose/docker-compose.nginx.yml
      service: nginx
    volumes:
      - /var/www/portal/cms/static:/var/www/portal/cms/static
      - /var/www/portal/cms/media:/var/www/portal/cms/media
      - /var/www/portal/portal/media:/var/www/portal/portal/media
      - /var/www/portal/portal/static:/var/www/portal/portal/static

  memcached:
    extends:
      file: docker-compose.memcached.yml
      service: memcached

  redis:
    extends:
      file: docker-compose.redis.yml
      service: redis

  rabbitmq:
    extends:
      file: docker-compose.rabbitmq.yml
      service: rabbitmq

  websockets:
    extends:
      file: docker-compose.websockets.yml
      service: websockets

  core:
    extends:
      file: docker-compose.core.yml
      service: core

  workers:
    extends:
      file: docker-compose.workers.yml
      service: workers

  cms:
    extends:
      file: docker-compose.cms.yml
      service: cms

volumes:
  portal_es_data:
  portal_redis_data:
  portal_rabbitmq_data:
