version: "3.8"
services:
  nginx:
    extends:
      file: ${CAMINO_HOME}/conf/compose/docker-compose.nginx.yml
      service: nginx
    volumes:
      - ${CAMINO_HOME}/conf/nginx/templates/sad.cms.conf.template:/etc/nginx/templates/default.conf.template
      - ${CAMINO_HOME}/conf/uwsgi/uwsgi_params:/etc/nginx/uwsgi_params
      - /var/www/portal/cms/static:/var/www/portal/cms/static
      - /var/www/portal/cms/media:/var/www/portal/cms/media

  cms:
    extends:
      file: docker-compose.cms.yml
      service: cms
