version: "3.8"
services:
  nginx:
    image: nginx
    volumes:
      - ${CAMINO_HOME}/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CAMINO_HOME}/conf/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - ${CAMINO_HOME}/conf/nginx/robots.txt.default:/var/www/robots.txt:ro
      - /etc/ssl/dhparam.pem:/etc/ssl/dhparam.pem:ro
    ports:
      - 80:80
      - 443:443
    container_name: portal_nginx
    environment:
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
    logging:
      driver: syslog
      options:
        tag: portal_nginx
    restart: always
