version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    container_name: portal_nginx
    logging:
      driver: syslog
      options:
        tag: portal_nginx
    restart: always
