version: "3.8"
services:
  workers:
    extends:
      file: docker-compose.core.yml
      service: core
    volumes:
      - ${CAMINO_HOME}/conf/portal/settings_secret.py:/srv/www/portal/server/portal/settings/settings_secret.py:ro
      - ${CAMINO_HOME}/conf/portal/settings_custom.py:/srv/www/portal/server/portal/settings/settings_custom.py
    command: sh -c "celery -A portal beat -l info --pidfile= --schedule=/tmp/celerybeat-schedule & 
             celery -A portal worker -Q default,indexing,files,api,onboard --concurrency=2"
    container_name: portal_workers
    logging:
      driver: syslog
      options:
        tag: portal_workers
    restart: always
