# Default CSP style-src and script-src extras for service.conf.template.
#    Override in Core-Portal-Deployments repo for service-specific domains.
map $host $csp_style_extra {
    default "";
}
map $host $csp_script_extra {
    default "";
}
