version: "3.8"
services:
  websockets:
    image: ${PORTAL_IMAGE}:${PORTAL_TAG}
    command: 'daphne -b 0.0.0.0 -p 9000 -e ssl:443:privateKey=/etc/ssl/private/portal.key:certKey=/etc/ssl/certs/portal.cer --root-path=/srv/www/portal/server --access-log - --proxy-headers portal.asgi:application'
    volumes:
      - ./conf/portal/settings_secret.py:/srv/www/portal/server/portal/settings/settings_secret.py
      - ./conf/portal/settings_custom.py:/srv/www/portal/server/portal/settings/settings_custom.py
    container_name: portal_websockets
    logging:
      driver: syslog
      options:
        tag: portal_websockets
    restart: always
